# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/release.yml # https://rhysd.github.io/actionlint/

name: Release-Tag
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

  Release-Build-and-Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Fetch Repository Tags
      run: |
        misc/version.sh
        git fetch --unshallow
        git describe --tags --exact-match 2>/dev/null || git describe
        git cat-file -t $GITHUB_REF_NAME

    - name: Prepare CI Image
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} |
          time misc/docker_build misc/Dockerfile.focal ghcr.io/tim-janik/anklang/anklang-ci $GITHUB_ACTOR
        misc/docker_run sudo chown ubuntu:ubuntu -R /anklang/

    - name: Build release assets
      run: |
        misc/docker_run misc/mkassets.sh
        misc/docker_clean

    - name: Release Upload
      id: ghrelease
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files:      assets/*
        body_path:  assets.txt

    - name: Release Info
      run: |
        echo URL: ${{ steps.ghrelease.outputs.url }}

  Ping-IRC:
    if: always()
    needs: [Release-Build-and-Upload]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Jobs
      run: |
        echo '${{ needs.Release-Build-and-Upload.result }}'
        test success = '${{ needs.Release-Build-and-Upload.result }}'
    - name: Ping IRC
      if: always()
      run: |
        R='${{ github.repository }}' && R=${R#*/}
        B='${{ github.ref }}' && B=${B#refs/heads/}
        S='${{ job.status }}' && URL='${{ github.event.head_commit.url }}'
        U='${{ github.actor }}' && B="$(git branch --show-current)"
        MSG=$(git log -1 --format='%s')
        .github/workflows/ircbot.py -q -j "#Anklang" -R "$R" -U "$U" -D "$B" -S "$S" "$MSG" "$URL"
