# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['trunk', 'wip/**']

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - uses: actions/cache@v3.0.6
      with:
        path: ~/ghcache/
        key: ${{ runner.os }}-build-${{ hashFiles ('misc/Dockerfile-apt') }}
    - name: Load Docker Image Cache
      run: test ! -r ~/ghcache/anklang-dockerimage.tar || docker load -i ~/ghcache/anklang-dockerimage.tar
    - name: Show Version
      run: |
        misc/version.sh
        misc/dbuild.sh misc/version.sh
    - name: Build Project
      run: |
        misc/dbuild.sh make SKIP_LATEX=true -j `nproc`
    - name: Run Tests
      run: |
        misc/dbuild.sh make check
    - name: Ping IRC
      if: always()
      run: |
        S="${{ job.status }}" && URL="${{ github.event.head_commit.url }}"
        N="$(git log -1 --format="%cL")" && B="$(git branch --show-current)"
        MSG=$(git log -1 --format="%s")
        .github/workflows/ircbot.py -q -j "#Anklang" -n AnklangGH -U "$N" -D "$B" -S "$S" "$MSG" "$URL"
    - name: Save Docker Image Cache
      run: mkdir -p ~/ghcache/ && docker save anklang-dbuild -o ~/ghcache/anklang-dockerimage.tar
