# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['trunk', 'next', 'wip/**']
  pull_request:
    branches: ['trunk', 'next']

jobs:

  Test-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: ghcache
      with:
        path: ~/ghcache/
        key: ${{ runner.os }}-Ubuntu-${{ hashFiles ('misc/Dockerfile.focal', 'misc/dbuild.sh') }}
    - name: Load Docker Cache
      if: ${{ steps.ghcache.outputs.cache-hit == 'true' }}
      run: |
        test ! -r ~/ghcache/anklang-focal.tar || docker load -i ~/ghcache/anklang-focal.tar
    - name: Project Version
      run: |
        misc/version.sh
    - name: Prepare Ubuntu
      run: |
        misc/dbuild.sh -f focal misc/version.sh
    - name: Build Ubuntu
      run: |
        misc/dbuild.sh -f focal make -j`nproc` all pdf
    - name: Test Ubuntu
      run: |
        misc/dbuild.sh -f focal make check
    - name: Save Docker Cache
      if: ${{ steps.ghcache.outputs.cache-hit != 'true' }}
      run: |
        mkdir -p ~/ghcache/
        docker save anklang-focal -o ~/ghcache/anklang-focal.tar
        ls -al ~/ghcache/
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: |
          out/doc/copyright
          out/doc/*.pdf
          out/doc/[NR]*.html
    - name: End-to-end X11 Tests
      run: |
        misc/dbuild.sh -f focal make x11test-v
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: x11test
        path: out/x11test/

  Test-Arch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: ghcache
      with:
        path: ~/ghcache/
        key: ${{ runner.os }}-Arch-${{ hashFiles ('misc/Dockerfile.arch', 'misc/dbuild.sh') }}
    - name: Load Docker Cache
      if: ${{ steps.ghcache.outputs.cache-hit == 'true' }}
      run: |
        test ! -r ~/ghcache/anklang-arch.tar || docker load -i ~/ghcache/anklang-arch.tar
    - name: Prepare Arch
      run: |
        misc/dbuild.sh -f arch misc/version.sh
    - name: Build Arch
      run: |
        misc/dbuild.sh -f arch make SKIP_LATEX=true -j`nproc`
    - name: Test Arch
      run: |
        misc/dbuild.sh -f arch make check
    - name: Save Docker Cache
      if: ${{ steps.ghcache.outputs.cache-hit != 'true' }}
      run: |
        mkdir -p ~/ghcache/
        docker save anklang-arch -o ~/ghcache/anklang-arch.tar
        ls -al ~/ghcache/

  Ping-IRC:
    if: always()
    needs: [Test-Ubuntu, Test-Arch]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Jobs
      run: |
        echo '${{ needs.Test-Ubuntu.result }}' '${{ needs.Test-Arch.result }}'
        test success = '${{ needs.Test-Ubuntu.result }}'
        test success = '${{ needs.Test-Arch.result }}'
    - name: Ping IRC
      if: always()
      run: |
        S='${{ job.status }}' && URL='${{ github.event.head_commit.url }}'
        N="$(git log -1 --format='%cL')" && B="$(git branch --show-current)"
        MSG=$(git log -1 --format='%s')
        .github/workflows/ircbot.py -q -j "#Anklang" -U "$N" -D "$B" -S "$S" "$MSG" "$URL"
