# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['trunk', 'next', 'wip/**']
  pull_request:
    branches: ['trunk', 'next']

jobs:

  Focal-CI:
    runs-on: ubuntu-latest
    steps:
    # Checkout and fix actions/checkout messing up annotation of the fetched tag: actions/checkout#290
    - uses: actions/checkout@v4
      with: { fetch-depth: 0, show-progress: false }
    - run: git fetch -f --tags
    # Docker build - use BuildKit and Github action API for reliable caching
    - uses: docker/setup-buildx-action@v2.10.0
    - run: docker buildx create --use --driver=docker-container # multi-platform, exports cache, needs --load
    - uses: docker/build-push-action@v4
      with: # docker build -t cifocal:latest -f misc/Dockerfile.focal misc
        tags: cifocal:latest
        file: misc/Dockerfile.focal
        context: misc/
        cache-from: type=gha
        cache-to:   type=gha,mode=max
        load: true
    # Run CI Stages
    - name: Run CI Stages
      run: |
        time misc/cirun.sh --check --assets --x11
    - uses: actions/upload-artifact@v3
      if: success()
      with: { name: docs, path: out/anklang-docs/ }
    - uses: actions/upload-artifact@v3
      if: success()
      with: { name: assets, path: assets/ }
    # Upload http://tim-janik.github.io/docs/anklang
    - name: Upload http://tim-janik.github.io/docs/anklang
      if: github.ref == 'refs/heads/trunk'
      run: |
        (umask 0077 && echo "${{ secrets.SSH_ID_GHDOCS4ANKLANG_ECDSA }}" > ~/.id4poxy)
        time misc/cirun.sh --poxy-key ~/.id4poxy

  Arch-Replay:
    runs-on: ubuntu-latest
    env: # INTERACTIVE: docker run -i --cap-add SYS_PTRACE -v $PWD:/anklang ...
      RUN: docker run -v /home/runner/work/anklang/anklang:/anklang -w /anklang/ -t --rm ciarch
    steps:
    # Checkout and fix actions/checkout messing up annotation of the fetched tag: actions/checkout#290
    - uses: actions/checkout@v4
      with: { fetch-depth: 0, show-progress: false }
    - run: git fetch -f --tags
    # Docker build - use BuildKit and Github action API for reliable caching
    - uses: docker/setup-buildx-action@v2.10.0
    - run: docker buildx create --use --driver=docker-container # multi-platform, exports cache, needs --load
    - uses: docker/build-push-action@v4
      with: # docker build -t ciarch:latest -f misc/Dockerfile.arch misc
        tags: ciarch:latest
        file: misc/Dockerfile.arch
        context: misc/
        cache-from: type=gha
        cache-to:   type=gha,mode=max
        load: true
    # Configure Build
    - name: Configure Build
      run: |
        git describe
        misc/version.sh
        echo 'prefix=/'		>  config-defaults.mk
        cat config-defaults.mk
        $RUN sudo chown builder:builder -R /anklang/	# gh-runner $UID != 1000
        $RUN misc/version.sh
    # Build binaries and check
    - name: Make all check
      run: |
        $RUN make -j`nproc` all
        $RUN make check
    # Run X11 GUI tests
    - name: Make x11test
      run: |
        $RUN make x11test-v
    # Artifact upload from x11test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: x11test
        path: out/x11test/
    # Restore gh-runner $UID
    - name: Cleanup
      run: |
        $RUN sudo chown `id -u`:`id -g` -R /anklang/

  Lunar-Clang-Tidy:
    runs-on: ubuntu-latest
    env: # INTERACTIVE: docker run -i --cap-add SYS_PTRACE -v $PWD:/anklang ...
      RUN: docker run -v /home/runner/work/anklang/anklang:/anklang -w /anklang/ -t --rm cilunar
    steps:
    # Checkout and fix actions/checkout messing up annotation of the fetched tag: actions/checkout#290
    - uses: actions/checkout@v4
      with: { fetch-depth: 0, show-progress: false }
    - run: git fetch -f --tags
    # Docker build - use BuildKit and Github action API for reliable caching
    - uses: docker/setup-buildx-action@v2.10.0
    - run: docker buildx create --use --driver=docker-container # multi-platform, exports cache, needs --load
    - uses: docker/build-push-action@v4
      with: # docker build -t cilunar:latest -f misc/Dockerfile.lunar misc
        tags: cilunar:latest
        file: misc/Dockerfile.lunar
        context: misc/
        cache-from: type=gha
        cache-to:   type=gha,mode=max
        load: true
    # Configure Build
    - name: Configure Build
      run: |
        git describe
        misc/version.sh
        echo 'prefix=/'			>  config-defaults.mk
        echo 'CC=clang-17'		>> config-defaults.mk
        echo 'CXX=clang++-17'		>> config-defaults.mk
        echo 'CLANG_TIDY=clang-tidy-17'	>> config-defaults.mk
        cat config-defaults.mk
        cat config-defaults.mk
        $RUN sudo chown ubuntu:ubuntu -R /anklang/	# gh-runner $UID != 1000
        $RUN misc/version.sh
    # Build binaries, docs and check
    - name: Make all check
      run: |
        $RUN make -j`nproc` all
        $RUN make check
    - name: Make clang-tidy
      run: |
        $RUN make -j`nproc` clang-tidy
    # Artifact upload from clang-tidy
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        name: clang-tidy
        path: out/clang-tidy/
    # Restore gh-runner $UID
    - name: Cleanup
      run: |
        $RUN sudo chown `id -u`:`id -g` -R /anklang/

  Ping-IRC:
    if: always()
    needs: [Focal-CI, Arch-Replay, Lunar-Clang-Tidy]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Jobs
      run: |
        echo '${{ needs.Focal-CI.result }}' '${{ needs.Arch-Replay.result }}' '${{ needs.Lunar-Clang-Tidy.result }}'
        test success = '${{ needs.Focal-CI.result }}'
        test success = '${{ needs.Arch-Replay.result }}'
        test success = '${{ needs.Lunar-Clang-Tidy.result }}'
    - name: Ping IRC
      if: always()
      run: |
        R='${{ github.repository }}' && R=${R#*/}
        B='${{ github.ref }}' && B=${B#refs/heads/}
        S='${{ job.status }}' && URL='${{ github.event.head_commit.url }}'
        U='${{ github.actor }}' && B="$(git branch --show-current)"
        MSG=$(git log -1 --format='%s')
        .github/workflows/ircbot.py -q -j "#Anklang" -R "$R" -U "$U" -D "$B" -S "$S" "$MSG" "$URL"
