# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['trunk', 'wip/**']

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show Version
      run: |
        misc/version.sh
        misc/dbuild.sh --no-tex -i misc/version.sh
    - name: Build Project
      run: misc/dbuild.sh --no-tex -i make SKIP_LATEX=true -j `nproc`
    - name: Run Tests
      run: misc/dbuild.sh --no-tex -i make check
    - name: Ping IRC
      if: always()
      run: |
        S="${{ job.status }}" && URL="${{ github.event.head_commit.url }}"
        N="$(git log -1 --format="%cL")" && B="$(git branch --show-current)"
        MSG=$(git log -1 --format="%s")
        .github/workflows/ircbot.py -q -j "#Anklang" -n AnklangGH -U "$N" -D "$B" -S "$S" "$MSG" "$URL"
