# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['trunk', 'next', 'wip/**']
  pull_request:
    branches: ['trunk', 'next']

jobs:

  Jammy-Docs:
    runs-on: ubuntu-latest
    env: # INTERACTIVE: docker run -i --cap-add SYS_PTRACE -v $PWD:/anklang ...
      RUN: docker run -v /home/runner/work/anklang/anklang:/anklang -w /anklang/ -t --rm cijammy
    steps:
    # Checkout and fix actions/checkout messing up annotation of the fetched tag: actions/checkout#290
    - uses: actions/checkout@v4
      with: { fetch-depth: 0, show-progress: false }
    - run: git fetch -f --tags
    # Docker build - use BuildKit and Github action API for reliable caching
    - uses: docker/setup-buildx-action@v2.10.0
    - run: docker buildx create --use --driver=docker-container # multi-platform, exports cache, needs --load
    - uses: docker/build-push-action@v4
      with: # docker build -t cijammy:latest -f misc/Dockerfile.jammy misc
        tags: cijammy:latest
        file: misc/Dockerfile.jammy
        context: misc/
        cache-from: type=gha
        cache-to:   type=gha,mode=max
        load: true
    # Configure Build
    - name: Configure Build
      run: |
        git describe
        misc/version.sh
        echo 'prefix=/'		>  config-defaults.mk
        echo 'CC=clang'		>> config-defaults.mk
        echo 'CXX=clang++'	>> config-defaults.mk
        (umask 0077 && echo "${{ secrets.SSH_ID_GHDOCS4ANKLANG_ECDSA }}" > .git/.ssh_id_ghdocs4anklang)
        cat config-defaults.mk
        $RUN sudo chown ubuntu:ubuntu -R /anklang/	# gh-runner $UID != 1000
        $RUN misc/version.sh
        $RUN clang++ --version
    # Build binaries, docs and check
    - name: Make all pdf check
      run: |
        $RUN make -j`nproc` all pdf
        $RUN make check
    # Artifact upload from make install
    - name: Make install
      run: |
        $RUN make install DESTDIR=inst
        $RUN cp -a inst/share/doc/anklang/ out/anklang-docs/
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        name: docs
        path: out/anklang-docs/
    - name: Upload http://tim-janik.github.io/docs/anklang
      if: github.ref == 'refs/heads/trunk'
      run: |
        $RUN doc/poxy.sh -b -u
    # Restore gh-runner $UID
    - name: Cleanup
      run: |
        $RUN sudo chown `id -u`:`id -g` -R /anklang/

  Arch-Replay:
    runs-on: ubuntu-latest
    env:
      DOCKER_RUN: docker run --cap-add SYS_PTRACE -v /home/runner/work/anklang/anklang/:/anklang/ -w /anklang/ -t --rm anklang-arch
    steps:
    - uses: actions/checkout@v3
    - name: Fetch last release tag
      run: |
        git fetch --unshallow
        git describe
    - name: Prepare CI Image
      # Build docker image using latest package as cache
      run: |
        docker --version
        set -x
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker pull ghcr.io/$GITHUB_REPOSITORY/anklang-ci:arch-latest || true
        time docker build -f misc/Dockerfile.arch -t anklang-arch misc/ --cache-from=ghcr.io/$GITHUB_REPOSITORY/anklang-ci:arch-latest
        docker tag anklang-arch ghcr.io/$GITHUB_REPOSITORY/anklang-ci:arch-latest
        docker push ghcr.io/$GITHUB_REPOSITORY/anklang-ci:arch-latest || true
        $DOCKER_RUN env </dev/null |& cat
    - name: Configure Build
      run: |
        echo 'prefix=/'		>  config-defaults.mk
        cat config-defaults.mk
        $DOCKER_RUN sudo chown builder:builder -R /anklang/
        $DOCKER_RUN misc/version.sh
    - name: Make all check
      run: |
        $DOCKER_RUN make -j`nproc` all
        $DOCKER_RUN make check
    - name: Make x11test
      run: |
        $DOCKER_RUN make x11test-v
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: x11test
        path: out/x11test/
    - name: Cleanup
      run: |
        $DOCKER_RUN sudo chown `id -u`:`id -g` -R /anklang/

  Lunar-Clang-Tidy:
    runs-on: ubuntu-latest
    env: # INTERACTIVE: docker run -i --cap-add SYS_PTRACE -v $PWD:/anklang ...
      RUN: docker run -v /home/runner/work/anklang/anklang:/anklang -w /anklang/ -t --rm cilunar
    steps:
    # Checkout and fix actions/checkout messing up annotation of the fetched tag: actions/checkout#290
    - uses: actions/checkout@v4
      with: { fetch-depth: 0, show-progress: false }
    - run: git fetch -f --tags
    # Docker build - use BuildKit and Github action API for reliable caching
    - uses: docker/setup-buildx-action@v2.10.0
    - run: docker buildx create --use --driver=docker-container # multi-platform, exports cache, needs --load
    - uses: docker/build-push-action@v4
      with: # docker build -t cilunar:latest -f misc/Dockerfile.lunar misc
        tags: cilunar:latest
        file: misc/Dockerfile.lunar
        context: misc/
        cache-from: type=gha
        cache-to:   type=gha,mode=max
        load: true
    # Configure Build
    - name: Configure Build
      run: |
        git describe
        misc/version.sh
        echo 'prefix=/'			>  config-defaults.mk
        echo 'CC=clang-17'		>> config-defaults.mk
        echo 'CXX=clang++-17'		>> config-defaults.mk
        echo 'CLANG_TIDY=clang-tidy-17'	>> config-defaults.mk
        cat config-defaults.mk
        cat config-defaults.mk
        $RUN sudo chown ubuntu:ubuntu -R /anklang/	# gh-runner $UID != 1000
        $RUN misc/version.sh
    # Build binaries, docs and check
    - name: Make all check
      run: |
        $RUN make -j`nproc` all
        $RUN make check
    - name: Make clang-tidy
      run: |
        $RUN make -j`nproc` clang-tidy
    # Artifact upload from make install
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        name: clang-tidy
        path: out/clang-tidy/
    # Restore gh-runner $UID
    - name: Cleanup
      run: |
        $RUN sudo chown `id -u`:`id -g` -R /anklang/

  Ping-IRC:
    if: always()
    needs: [Jammy-Docs, Arch-Replay, Lunar-Clang-Tidy]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Jobs
      run: |
        echo '${{ needs.Jammy-Docs.result }}' '${{ needs.Arch-Replay.result }}' '${{ needs.Lunar-Clang-Tidy.result }}'
        test success = '${{ needs.Jammy-Docs.result }}'
        test success = '${{ needs.Arch-Replay.result }}'
        test success = '${{ needs.Lunar-Clang-Tidy.result }}'
    - name: Ping IRC
      if: always()
      run: |
        R='${{ github.repository }}' && R=${R#*/}
        B='${{ github.ref }}' && B=${B#refs/heads/}
        S='${{ job.status }}' && URL='${{ github.event.head_commit.url }}'
        U='${{ github.actor }}' && B="$(git branch --show-current)"
        MSG=$(git log -1 --format='%s')
        .github/workflows/ircbot.py -q -j "#Anklang" -R "$R" -U "$U" -D "$B" -S "$S" "$MSG" "$URL"
